include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    always_use_package_imports: true
    directives_ordering: true
    avoid_relative_lib_imports: true
    sized_box_for_whitespace: true
    use_super_parameters: true
    use_colored_box: true
    avoid_unnecessary_containers: true
